Repository knative-extensions/net-kourier, pull requests merged in 2020-11, with the labels that each got.

#287 Remove unused make targets and drop duplicated config
  Makefile
  conf/envoy-bootstrap.yaml
Labels: approved, cla: yes, lgtm, size/M

#302 Widen linter coverage and fix existing issues
  .golangci.yaml
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#291 Refactor ExtAuthz config as a global config that's only read once
  go.mod
  pkg/config/config.go
  pkg/config/ext_authz.go
  pkg/envoy/ext_authz.go
  pkg/envoy/http_connection_manager.go
  pkg/envoy/lb_endpoint.go
  pkg/generator/caches.go
  pkg/reconciler/ingress/controller.go
  test/extauthz/integration_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#301 Remove unused Dockerfile
  Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#300 Remove defunct make target for conformance tests
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#298 Refactor ingress translator to preallocate much more aggressively
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: approved, cla: yes, lgtm, size/L

#303 Simplify set creation through constructor
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/XS

#304 Update instructions for local cluster setup
  Makefile
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#276 Optimize cache warmup on startup
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/L

#305 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#306 Drop handling of unnecessary ingresses in cache
  pkg/generator/caches.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#308 Pass nil maps instead of 0-len maps to avoid a few allocations
  pkg/envoy/headers.go
  pkg/generator/status_vhost.go
Labels: approved, cla: yes, lgtm, size/XS

#309 Make VirtualHost generators return pointers directly
  pkg/envoy/listener_test.go
  pkg/envoy/virtual_host.go
  pkg/generator/caches.go
  pkg/generator/ingress_translator.go
  pkg/generator/status_vhost.go
Labels: approved, cla: yes, lgtm, size/S

#307 Cleanup some cache helpers and remove indirections
  pkg/generator/caches.go
  pkg/generator/caches_test.go
Labels: approved, cla: yes, lgtm, size/S

#311 Remove unnecessary ingress -> cluster mapping
  pkg/generator/caches.go
Labels: approved, cla: yes, lgtm, size/M

#313 Reduce big-O of the conflict check to O(c)
  pkg/generator/caches.go
Labels: approved, cla: yes, lgtm, size/M

#310 Use NamespacedName in a few places to make interfaces more strongly typed
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/cluster_cache.go
  pkg/generator/ingress_translator.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/M

#312 Drop all usages of Knative types on caching layer
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
Labels: approved, cla: yes, lgtm, size/S

#316 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#317 Remove unnecessary YAML configuration from test/config
  .github/workflows/kind-e2e.yaml
  test/config/200-ingress.yaml
  test/config/200-service-account.yaml
  test/config/201-clusterrole-core.yaml
  test/config/config-autoscaler.yaml
  test/config/config-defaults.yaml
  test/config/config-logging.yaml
  test/config/config-network.yaml
Labels: approved, cla: yes, lgtm, size/L

#319 Simplify unit test targets a bit
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#320 Use 'auto' for coverage checks to rely on the current actual coverage
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#322 Split envoy package into API and Server
  pkg/envoy/api/cluster.go
  pkg/envoy/api/cluster_test.go
  pkg/envoy/api/headers.go
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/lb_endpoint.go
  pkg/envoy/api/lb_endpoint_test.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/envoy/api/route.go
  pkg/envoy/api/route_test.go
  pkg/envoy/api/virtual_host.go
  pkg/envoy/api/weighted_cluster.go
  pkg/envoy/server/callbacks.go
  pkg/envoy/server/xds_server.go
  pkg/generator/caches.go
  pkg/generator/generator.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/generator/status_vhost.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#315 Inline slice building functions to iterate only once
  pkg/generator/caches.go
Labels: approved, cla: yes, lgtm, size/M

#318 Fix the 'test-integration' target of the Makefile to successfully run tests locally
  Makefile
  test/e2e-kind.sh
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/M

#324 Use correct name of example service in "utils/setup.sh"
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#326 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#321 Split config into files and rename the folder to config
  .github/workflows/kind-e2e.yaml
  README.md
  config/100-namespace.yaml
  config/200-serviceaccount.yaml
  config/300-controller.yaml
  config/300-gateway.yaml
  hack/release.sh
  test/e2e-common.sh
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/L

#328 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#314 Remove a few shallow debug logs to avoid passing loggers around
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/cluster_cache.go
  pkg/generator/cluster_cache_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#329 Use 'global' client instead of passing it through in each request
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#325 Move code to where it is used and remove 'knative' package
  pkg/config/config.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/knative/ingress.go
  pkg/knative/ingress_rule.go
  pkg/knative/ingress_rule_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/L

#330 Avoid certificate conversion to string from secret
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/generator.go
  pkg/generator/ingress_translator_test.go
Labels: approved, cla: yes, lgtm, size/M

#331 Update RBAC resources to v1
  config/200-serviceaccount.yaml
Labels: approved, cla: yes, lgtm, size/S

#333 Use a secret informer to get secrets
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/controller.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#336 Collapse slices, collapse return values and remove whitespace
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/envoy/api/route.go
  pkg/envoy/api/route_test.go
  pkg/envoy/api/virtual_host.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/L

#337 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#332 Reduce unnecessary RBAC rules
  config/200-serviceaccount.yaml
Labels: approved, cla: yes, lgtm, size/XS

#335 Refactor lister generator to not rely on mutability
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
Labels: approved, cla: yes, lgtm, size/L

#338 Do not reconcile endpoints if the ready addresses haven't changed
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/M

#339 Make sure to delete watchers if the observer is removed
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#340 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#341 Use external connection manager for SNI based listener too
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/generator.go
Labels: approved, cla: yes, lgtm, size/L

#342 Deduplicate SNIMatches to optimize configuration memory usage
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/caches.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/generator/sni.go
  pkg/generator/sni_test.go
Labels: approved, cla: yes, lgtm, size/L

#344 Actually use the sorted slice in test
  pkg/generator/sni_test.go
Labels: approved, cla: yes, lgtm, size/XS

#346 Remove unused NewRouteStatusOK
  pkg/envoy/api/route.go
  pkg/envoy/api/route_test.go
Labels: approved, cla: yes, lgtm, size/S

#345 Implement HostRewrite feature of Ingress
  .github/workflows/kind-e2e.yaml
  pkg/envoy/api/route.go
  pkg/envoy/api/route_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/generator/status_vhost.go
  test/e2e-kind.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#349 Bump gotest.tools to the latest version
  go.mod
  go.sum
  pkg/envoy/api/cluster_test.go
  pkg/envoy/api/headers_test.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/lb_endpoint_test.go
  pkg/envoy/api/listener_test.go
  pkg/envoy/api/route_test.go
  pkg/envoy/api/virtual_host_test.go
  pkg/envoy/api/weighted_cluster_test.go
  pkg/generator/caches_test.go
  pkg/generator/cluster_cache_test.go
  pkg/generator/ingress_translator_test.go
  pkg/generator/sni_test.go
  test/extauthz/extauthz_test.go
  vendor/gotest.tools/v3/LICENSE
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/internal/assert/assert.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/difflib/LICENSE
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/diff.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#348 Cleanup tests by using proper assertions etc
  pkg/generator/caches_test.go
  pkg/generator/cluster_cache_test.go
  pkg/generator/ingress_translator_test.go
Labels: approved, cla: yes, lgtm, size/L

#347 Fix cluster-cache test to be correct and quicker
  pkg/generator/cluster_cache.go
  pkg/generator/cluster_cache_test.go
Labels: approved, cla: yes, lgtm, size/M

#350 Rewrite ingress translator tests for more coverage
  pkg/generator/ingress_translator_test.go
Labels: approved, cla: yes, lgtm, size/XL

#351 Avoid setting the envoy snapshot twice per reconcile
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#355 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#354 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/proc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#353 Generate listers and routes when actually needed and don't 'cache' them
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/L

#357 Cleanup functions around getting/setting snapshots
  pkg/envoy/server/xds_server.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#358 Bump envoy version to 1.14.4
  config/300-gateway.yaml
Labels: approved, cla: yes, lgtm, size/XS

#359 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#362 Fix all deprecation warnings from Envoy
  config/300-gateway.yaml
  pkg/config/ext_authz.go
Labels: approved, cla: yes, lgtm, size/M

#363 Use Any machinery to construct TypedConfigs everywhere
  pkg/envoy/api/virtual_host.go
  pkg/generator/status_vhost.go
Labels: approved, cla: yes, lgtm, size/S

#364 Use IDHasher from envoy's library
  pkg/envoy/server/xds_server.go
Labels: approved, cla: yes, lgtm, size/S

#366 Add version label to all resources
  config/100-namespace.yaml
  config/200-serviceaccount.yaml
  config/300-controller.yaml
  config/300-gateway.yaml
Labels: approved, cla: yes, lgtm, size/S

#365 Use CallbackFuncs type and don't abort stream on push error
  pkg/envoy/server/callbacks.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/M

#370 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#367 Don't even try to probe services that have a domain conflict
  .github/workflows/kind-e2e.yaml
  pkg/reconciler/ingress/ingress.go
  test/e2e-kind.sh
  test/e2e-tests.sh
  test/e2e/conflict_test.go
Labels: approved, cla: yes, lgtm, size/L

#368 [RELEASE-0.19] Don't even try to probe services that have a domain conflict
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#369 [RELEASE-0.18] Don't even try to probe services that have a domain conflict
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#372 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#352 Cleanup the reconciler file itself a bit
  pkg/generator/generator.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#373 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#371 Name envoy config resources in a non-conflicting way
  go.mod
  go.sum
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#375 Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#376 [RELEASE-0.19] Backport update to Envoy 1.14.4
  config/300-gateway.yaml
  go.sum
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: approved, cla: yes, lgtm, size/M

#378 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#379 Simplify scripts a little
  test/e2e-kind.sh
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/S

#380 Drop vendoring of helloworld image
  hack/tools.go
  vendor/knative.dev/networking/test/test_images/helloworld/helloworld.go
  vendor/knative.dev/networking/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/networking/test/test_images/helloworld/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#377 Setup an upgrade test to catch upgrade regressions
  .github/workflows/kind-e2e-upgrade.yaml
  test/e2e-upgrade-kind.sh
  test/upgrade/probe_test.go
Labels: approved, cla: yes, lgtm, size/L

#382 Add a bounds check to the ExtAuth port number
  pkg/config/ext_authz.go
Labels: approved, cla: yes, lgtm, size/XS

#384 Fix deprecation warnings
  test/ha/ha.go
Labels: approved, cla: yes, lgtm, size/XS

#385 Fix max port comparison
  pkg/config/ext_authz.go
Labels: approved, cla: yes, lgtm, size/S
