Repository knative-extensions/net-kourier, pull requests merged in 2020-04, with the labels that each got.

#8 Add defaulting and status initialization to the reconciler.
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#9 Remove unnecessary workaround to init split percentages
  pkg/generator/ingress_translator.go
Labels: approved, cla: yes, lgtm, size/S

#11 Add release.sh to unblock nightly releases
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#12 [master] Format markdown
  CHANGELOG.md
  README.md
  docs/generated_envoy_config.md
  docs/knative_e2e_tests.md
Labels: approved, cla: yes, lgtm, size/L

#13 Update serving to 0.13.2 in script to setup local env
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#14 Makefile: add target to run conformance tests
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#15 Delete redundant 'SimpleScenario' integration test
  test/integration_test.go
Labels: approved, cla: yes, lgtm, size/M

#16 Makefile: fix test-integration target
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#17 hack/update-deps: delete comment that no longer applies
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#19 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/network/ingress/ingress.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#21 Add PHONY targets to makefile
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#20 [master] golang format tools
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#18 Reuse knative prober
  pkg/config/config.go
  pkg/generator/caches.go
  pkg/generator/generator.go
  pkg/generator/ingress_translator.go
  pkg/generator/status_vhost.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/status.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#22 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#23 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#25 Enable HA controller setup
  cmd/kourier/main.go
  deploy/kourier-knative.yaml
  pkg/config/config.go
Labels: approved, cla: yes, lgtm, size/M

#26 Remove clusteringress from kourier manifest and test script
  README.md
  deploy/kourier-knative.yaml
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#27 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#28 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/cleanup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#29 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#31 Disable TestRetry to unblock releases.
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#33 Add wait for LB call
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#32 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#34 Use ko in deployment yaml
  deploy/kourier-knative.yaml
  hack/release.sh
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#35 Re-enable TestRetry
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#36 Freeze deps for 0.14 release.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#37 Update serving to 0.14.0 in script to set up local env
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#38 README: update for v0.14.0
  README.md
Labels: approved, cla: yes, lgtm, size/S

#40 Run net-kourier as non-root
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#39 Validate Ingress before adding it to the cache: Avoid duplicated domains
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
  pkg/knative/ingress.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/L

#43 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e_constants.go
  vendor/knative.dev/serving/test/util.go
  vendor/knative.dev/serving/test/v1alpha1/configuration.go
  vendor/knative.dev/serving/test/v1alpha1/route.go
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#44 Remove unused http gateway
  pkg/envoy/xds_server.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/S

#46 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/cached.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#47 Filter global resyncs to only use kourier class too.
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/M

#49 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#45 Reduce unknown cluster retries
  pkg/config/config.go
  pkg/envoy/xds_server.go
  pkg/generator/ingress_translator.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#50 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#51 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/conformance/ingress/README.md
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#52 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/test/conformance/ingress/README.md
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#53 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#54 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
