Repository knative-extensions/net-kourier, pull requests merged in 2020-07, with the labels that each got.

#115 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#116 Pin to knative.dev/serving@release-16
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#119 Update serving to 0.16.0 in local setup script
  README.md
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#120 Update envoy to the latest available version
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#121 Prepare for new leaderelection.
  go.mod
  go.sum
  test/e2e-common.sh
  test/e2e-tests.sh
  test/ha/kourier_control_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#123 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#130 Add a sleep before stopping the gateway
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/XS
