Repository knative-extensions/net-kourier, pull requests merged in 2020-06, with the labels that each got.

#88 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#89 Re-enable ingress conformance
  go.mod
  go.sum
  test/conformance/ingress_test.go
  test/e2e-tests.sh
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/conformance/ingress/basic.go
  vendor/knative.dev/serving/test/conformance/ingress/grpc.go
  vendor/knative.dev/serving/test/conformance/ingress/headers.go
  vendor/knative.dev/serving/test/conformance/ingress/hosts.go
  vendor/knative.dev/serving/test/conformance/ingress/path.go
  vendor/knative.dev/serving/test/conformance/ingress/percentage.go
  vendor/knative.dev/serving/test/conformance/ingress/retry.go
  vendor/knative.dev/serving/test/conformance/ingress/run.go
  vendor/knative.dev/serving/test/conformance/ingress/timeout.go
  vendor/knative.dev/serving/test/conformance/ingress/tls.go
  vendor/knative.dev/serving/test/conformance/ingress/update.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility.go
  vendor/knative.dev/serving/test/conformance/ingress/websocket.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#90 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#91 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_lifecycle.go
  vendor/knative.dev/serving/test/conformance/ingress/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#94 Remove unused InternalKourierPath constant
  pkg/config/config.go
Labels: approved, cla: yes, lgtm, size/XS

#96 Preallocate slices.
  pkg/envoy/headers.go
  pkg/envoy/listener.go
  pkg/generator/caches.go
  pkg/generator/cluster_cache.go
  pkg/generator/cluster_cache_test.go
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/S

#97 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#72 Warm the internal config cache to avoid sending an empty snapshot.
  deploy/kourier-knative.yaml
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  vendor/knative.dev/serving/pkg/client/injection/client/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#99 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/route.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#100 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#101 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#103 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#104 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/clients.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#102 Update knative references to v0.15.0
  README.md
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/XS

#106 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#110 Tag Header based routing
  pkg/envoy/route.go
  pkg/envoy/route_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/status_vhost.go
Labels: approved, cla: yes, lgtm, size/M

#112 Fixes for kourier to run under istio.
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#114 Pin knative.dev/{pkg,test-infra,networking} to release-0.16
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
