Repository knative-extensions/net-kourier, pull requests merged in 2020-08, with the labels that each got.

#136 Use the readonly interfaces for the new leader election
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#139 Cleanup ingress reconciler file.
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#137 Initialize the envoy snapshot without waiting for cache sync
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/S

#126 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#141 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#142 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/conformance/ingress/basic.go
  vendor/knative.dev/serving/test/conformance/ingress/grpc.go
  vendor/knative.dev/serving/test/conformance/ingress/headers.go
  vendor/knative.dev/serving/test/conformance/ingress/hosts.go
  vendor/knative.dev/serving/test/conformance/ingress/path.go
  vendor/knative.dev/serving/test/conformance/ingress/percentage.go
  vendor/knative.dev/serving/test/conformance/ingress/retry.go
  vendor/knative.dev/serving/test/conformance/ingress/timeout.go
  vendor/knative.dev/serving/test/conformance/ingress/tls.go
  vendor/knative.dev/serving/test/conformance/ingress/update.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility.go
  vendor/knative.dev/serving/test/conformance/ingress/websocket.go
  vendor/knative.dev/serving/test/defaultsystem/system.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#143 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/test/conformance.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/defaultsystem/system.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e_constants.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#127 Enable chaos testing on net-kourier
  hack/tools.go
  test/config/chaosduck.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/ha/kourier_control_test.go
  vendor/knative.dev/pkg/kflag/OWNERS
  vendor/knative.dev/pkg/kflag/doc.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#146 Use latest envoy maistra proxy image available
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#129 Adapt k3d commands to the latest version of k3d.
  Makefile
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/S

#149 Pin some knative deps to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#150 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#153 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#154 Use HasSuffix for local domain check
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/XS

#156 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/register.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#132 Add missing perms for events and coordination via configmap.
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#151 Use knative-serving namespace for kourier control-plane
  README.md
  conf/envoy-bootstrap.yaml
  deploy/kourier-knative.yaml
  pkg/config/config.go
  pkg/knative/ingress.go
  pkg/reconciler/ingress/lister.go
  test/e2e-common.sh
  test/ha/kourier_control_test.go
  test/ha/kourier_gateway_test.go
  test/integration_test.go
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/L

#157 Enable Envoy debug log during tests
  deploy/kourier-knative.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#161 [master] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S

#162 Pin knative.dev/serving to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#164 Stop expanding cluster local hosts
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/knative/ingress_rule.go
  pkg/knative/ingress_rule_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/lister.go
Labels: approved, cla: yes, lgtm, size/L

#165 Add MarkLoadBalancerNotRead when status manager fails to probe
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS
