Repository knative-extensions/net-kourier, pull requests merged in 2020-09, with the labels that each got.

#170 Simplify ExtAuthz timeout computation.
  pkg/envoy/ext_authz.go
Labels: approved, cla: yes, lgtm, size/S

#168 Remove deprecated spec.visibility from KIngress
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/knative/ingress.go
  pkg/knative/ingress_rule.go
  pkg/knative/ingress_rule_test.go
  pkg/reconciler/ingress/lister.go
  test/ha/ha.go
Labels: approved, cla: yes, lgtm, size/M

#177 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#174 Use InsertProbe instead of InsertKourierHeaders
  pkg/generator/generator.go
  pkg/generator/ingress_translator.go
Labels: approved, cla: yes, lgtm, size/M

#178 Add linting config and fix issues.
  .golangci.yaml
  pkg/envoy/virtual_host.go
  pkg/knative/ingress_rule.go
  pkg/reconciler/ingress/lister.go
  test/extauthz/helpers.go
  test/extauthz/integration_test.go
  test/ha/kourier_control_test.go
Labels: approved, cla: yes, lgtm, size/M

#182 Remove redundant log message
  pkg/generator/generator.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#183 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#186 Add TOC folks to OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#187 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#188 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#191 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#194 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#197 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#201 Do not create EnvoyRoute if any of service/endpoint in the Ingress is not ready
  pkg/generator/ingress_translator.go
Labels: approved, cla: yes, lgtm, size/XS

#158 Enable beta tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#202 Avoid prober resync flood
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#203 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#199 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#205 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#206 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#207 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#208 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#210 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#209 [Automated] Fix misspellings
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#211 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#212 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#213 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#214 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#215 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#216 Pin serving to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#217 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#218 Enable extended linting and fix the respective issues
  .golangci.yaml
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator_test.go
  test/extauthz/helpers.go
  test/extauthz/integration_test.go
Labels: approved, cla: yes, lgtm, size/M
