Repository knative-extensions/net-kourier, pull requests merged in 2020-05, with the labels that each got.

#57 Multiple controller threads support
  cmd/kourier/main.go
  go.mod
  go.sum
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/generator.go
  pkg/reconciler/ingress/controller.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#59 Remove logrus dependency and use common logger.
  cmd/kourier/main.go
  go.mod
  pkg/envoy/xds_server.go
  pkg/generator/caches.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/M

#60 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#61 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/service_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#62 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#66 Fix module usage in presubmit tests and update scripts.
  hack/tools.go
  hack/update-deps.sh
  test/presubmit-tests.sh
  vendor/knative.dev/serving/test/test_images/helloworld/README.md
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.go
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/serving/test/test_images/helloworld/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#67 Move go.mod to 1.14 for consistency with all core repos.
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#65 remove unused const
  pkg/config/config.go
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#63 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#68 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#64 Remove 30s global resync
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/S

#69 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#71 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#73 Add codegen scripts for consistency.
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/M

#74 Tune back to go 1.13 to make integration tests run.
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#78 [RELEASE] Pin knative.dev/{pkg,test-infra} to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#79 Add `networking.knative.dev/ingress-provider: kourier` to resources.
  deploy/kourier-knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#75 Aligning test call with net-istio.
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#81 Bring back - Wait for Static IP to be hooked up
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#80 Graceful shutdown
  deploy/kourier-knative.yaml
  pkg/generator/status_vhost.go
  utils/setup.sh
Labels: approved, cla: yes, lgtm, size/M

#83 [RELEASE] Pin serving to 0.15.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#84 [POST-RELEASE] Track master branches again.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#77 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#85 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/test/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#86 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#87 Update go.mod to specify the module is go1.14
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
