Repository knative-extensions/net-kourier, pull requests merged in 2021-12, with the labels that each got.

#725 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#726 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#728 Bump Kourier Gateway (envoy) image version
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#729 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#731 Drop explicit indirect dependencies
  go.mod
  go.sum
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#732 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#733 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#735 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS
