Repository knative-extensions/net-kourier, pull requests merged in 2021-11, with the labels that each got.

#682 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#683 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#684 Document maturity levels in sandbox
  README.md
Labels: lgtm, approved, cla: yes, size/XS

#686 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/S

#687 Hardcode upgrade test version as detection doesn't work in actions
  test/e2e-upgrade-kind.sh
Labels: lgtm, approved, cla: yes, size/XS

#689 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, cla: yes, size/XS

#690 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#672 [release-0.26] create tls route when using one cert via environment value
  .github/workflows/knative-verify.yaml
  pkg/config/zz_generated.deepcopy.go
  pkg/generator/ingress_translator.go
  test/cert/certificate_test.go
  test/e2e-kind.sh
  test/generate-cert.sh
  test/upload-test-images.sh
Labels: lgtm, approved, size/L, cla: yes

#695 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#696 Revert "Hardcode upgrade test version as detection doesn't work in actions (#687)
  test/e2e-upgrade-kind.sh
Labels: lgtm, approved, cla: yes, size/XS

#692 Stop using deprecated HTTP2 api
  .github/workflows/kind-e2e.yaml
  pkg/config/ext_authz.go
  pkg/envoy/api/cluster.go
  pkg/envoy/api/cluster_test.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/extensions/upstreams/http/v3/http_protocol_options.pb.go
  vendor/github.com/envoyproxy/go-control-plane/envoy/extensions/upstreams/http/v3/http_protocol_options.pb.validate.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#697 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#694 Adds k8s recommended labels
  config/100-namespace.yaml
  config/200-bootstrap.yaml
  config/200-config.yaml
  config/200-serviceaccount.yaml
  config/300-controller.yaml
  config/300-gateway.yaml
  hack/release.sh
Labels: lgtm, size/M, approved, cla: yes, kind/enhancement

#699 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#698 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/M, approved, cla: yes

#700 Update README
  Makefile
  README.md
Labels: lgtm, size/M, approved, cla: yes

#701 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#703 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#704 Introduce `KOURIER_HTTPOPTION_DISABLED` env variable to disable redirect
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, approved, size/L, cla: yes

#707 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#708 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#709 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#710 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#712 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#713 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#715 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#716 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#714 Clean up test/e2e-common.sh
  test/e2e-common.sh
Labels: lgtm, size/M, approved, cla: yes

#717 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#719 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#723 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, cla: yes, size/XS

#724 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes
