Repository knative-extensions/net-kourier, pull requests merged in 2021-04, with the labels that each got.

#487 Update K8s versions for upgrade tests
  .github/workflows/kind-e2e-upgrade.yaml
Labels: cla: yes, lgtm, size/S

#486 Globally reconcile conflicted Ingresses on deletion
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: cla: yes, lgtm, size/S

#489 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#490 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#491 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#492 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#493 Mark network configured as soon as it is
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#494 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#496 Use reconciler defined key to filter
  pkg/reconciler/ingress/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#498 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#497 Fix potentially racy ingress deletion behavior
  pkg/reconciler/ingress/ingress.go
Labels: cla: yes, lgtm, size/S

#499 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#501 Drop --strict flag on ko
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#500 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#502 Move conflict-resync into ObserveDeletion handler
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#503 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#504 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#505 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: cla: yes, lgtm, size/L

#506 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#507 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
