Repository knative-extensions/net-kourier, pull requests merged in 2021-09, with the labels that each got.

#623 Bump default envoy version to 1.17
  config/300-gateway.yaml
Labels: lgtm, approved, cla: yes, size/XS

#624 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#625 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, cla: yes, size/XS

#627 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#626 Split RouteConfig for HTTP and HTTPS listeners
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, approved, size/L, cla: yes

#619 Support `httpProtocol: Redirected`
  pkg/envoy/api/route.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  test/e2e-kind.sh
  test/e2e-tests.sh
Labels: lgtm, approved, size/L, cla: yes

#630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#631 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#633 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#634 Set ValidateClusters in NewRouteConfig
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/generator/caches.go
Labels: lgtm, approved, cla: yes, size/S, kind/cleanup

#635 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#636 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#638 Reconcile only ingresses that reference the failing cluster
  pkg/generator/ingress_translator.go
  pkg/reconciler/ingress/controller.go
Labels: lgtm, size/M, approved, cla: yes

#640 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: lgtm, size/M, approved, cla: yes

#639 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#641 Drop K8s 1.19 as it's no longer supported
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, cla: yes, size/S

#643 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, cla: yes, size/S

#642 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/S

#644 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, cla: yes, size/XS

#645 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#646 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/S

#647 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, cla: yes, size/S

#648 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/S
