Repository knative-extensions/net-kourier, pull requests merged in 2022-05, with the labels that each got.

#827 Bump envoy version
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#836 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#835 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#837 Bump kind version to 0.12.0 for k8s 1.23.
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/XS

#841 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#842 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#814 Add config-network to resync trigger
  pkg/reconciler/ingress/controller.go
Labels: lgtm, approved, size/XS

#843 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#846 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#845 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/networking/test/test_images/retry/main.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/timeout/timeout.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#848 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#849 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
