Repository knative-extensions/net-kourier, pull requests merged in 2022-07, with the labels that each got.

#865 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#864 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#862 Support secret filtering informer
  cmd/kourier/main.go
  config/300-controller.yaml
  pkg/reconciler/informerfiltering/util.go
  pkg/reconciler/ingress/controller.go
  test/generate-upstream-cert.sh
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#869 Proxy protocol and SNI do not work together
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  test/proxyprotocol/proxyprotocol_test.go
Labels: lgtm, approved, size/L, kind/bug

#872 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#866 Add timeout config to Kourier
  .gitignore
  config/200-config.yaml
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/listener_test.go
  pkg/generator/caches.go
  test/e2e-kind.sh
  test/timeout/timeout_test.go
Labels: lgtm, approved, size/L, ok-to-test

#852 Isolate private ksvc using different envoy listener ports
  README.md
  config/200-config.yaml
  config/200-serviceaccount.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, kind/enhancement

#867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#878 Set no limit to the timeout by default
  config/200-config.yaml
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/envoy/api/http_connection_manager_test.go
  pkg/envoy/api/listener_test.go
Labels: lgtm, size/M, approved

#881 Bump Go version to 1.18
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#880 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#882 Bump go.mod to v1.18
  go.mod
  go.sum
Labels: lgtm, size/M, approved

#884 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#883 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/pkg/pool/doc.go
  vendor/knative.dev/pkg/pool/interface.go
  vendor/knative.dev/pkg/pool/pool.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#885 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
