Repository knative-extensions/net-kourier, pull requests merged in 2022-11, with the labels that each got.

#939 Bump ko version in kind
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/S

#948 gofmt 1.19
  pkg/generator/ingress_translator.go
  test/config/extauthz/http/src/main.go
Labels: lgtm, approved, size/XS

#944 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#951 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#936 Add private key provider support
  config/200-config.yaml
  pkg/config/configmap.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/caches.go
  vendor/github.com/envoyproxy/go-control-plane/contrib/envoy/extensions/private_key_providers/cryptomb/v3alpha/cryptomb.pb.go
  vendor/github.com/envoyproxy/go-control-plane/contrib/envoy/extensions/private_key_providers/cryptomb/v3alpha/cryptomb.pb.validate.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL
