Repository knative-extensions/net-kourier, pull requests merged in 2022-04, with the labels that each got.

#812 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#813 Use HTTP2 when service has HTTP2 port in the ports
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, approved, size/L

#816 drop knative.dev/release label
  README.md
  config/100-namespace.yaml
  config/200-bootstrap.yaml
  config/200-config.yaml
  config/200-serviceaccount.yaml
  config/300-controller.yaml
  config/300-gateway.yaml
  hack/release.sh
  test/config/chaosduck.yaml
  test/config/leader-election.yaml
  test/config/tls/config-network.yaml
Labels: lgtm, approved, size/S

#819 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#820 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#817 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/L

#822 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#823 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/S

#797 Set `80` port if k8s service omits the port
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, size/M, approved

#825 Bump k8s version in kind
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#824 All Hops Encrypted: alpha Kourier support for encrypted for internal traffic
  config/200-config.yaml
  config/300-gateway.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/generator/caches.go
  pkg/generator/caches_test.go
Labels: lgtm, approved, size/L

#828 Enable TLS on upgrade kind e2e
  .github/workflows/kind-e2e-upgrade.yaml
Labels: lgtm, approved, size/XS

#829 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#832 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#833 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#834 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
