Repository knative-extensions/net-kourier, pull requests merged in 2022-08, with the labels that each got.

#888 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#890 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#891 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#893 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#894 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#895 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#896 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#899 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#900 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#901 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#905 Made TLS 1.2 the minimum protocol version
  pkg/envoy/api/listener.go
Labels: lgtm, approved, size/XS, ok-to-test

#908 let README.md `port-forward` work with 200-bootstrap.yaml
  README.md
Labels: lgtm, approved, size/XS, ok-to-test

#906 Enable internal tls test on upgrade e2e
  .github/workflows/kind-e2e-upgrade.yaml
Labels: lgtm, approved, size/XS
