Repository knative-extensions/net-kourier, pull requests merged in 2022-03, with the labels that each got.

#780 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#781 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_other.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#778 disable ext_authz filter for http01 challenge
  go.mod
  pkg/envoy/api/route.go
  pkg/envoy/api/route_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, ok-to-test, kind/enhancement

#783 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#787 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#785 Ext auth service : remove `split_words` to honor `KOURIER_EXTAUTHZ*` env vars
  pkg/config/ext_authz.go
Labels: lgtm, approved, size/XS, ok-to-test, kind/bug

#789 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#788 Bump envoy version to v1.19
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#792 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#793 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#794 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#786 Ext auth service : add http/https protocol
  README.md
  pkg/config/ext_authz.go
  pkg/config/ext_authz_test.go
  test/config/extauthz/grpc/deployment.yaml
  test/config/extauthz/grpc/src/main.go
  test/config/extauthz/http/deployment.yaml
  test/config/extauthz/http/src/main.go
  test/e2e-kind.sh
Labels: lgtm, approved, size/XL, ok-to-test, kind/enhancement

#796 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#800 Adding code of conduct to reference knative/community's CoC
  code-of-conduct.md
Labels: lgtm, size/M, approved

#803 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#761 All Hops Encrypted: alpha Kourier support for encrypted backends
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
  hack/update-codegen.sh
  pkg/envoy/api/cluster.go
  pkg/envoy/api/cluster_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/config/testdata/config-network.yaml
  pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  test/config/config-network.yaml
  test/config/tls/config-network.yaml
  test/e2e-kind.sh
  test/e2e-upgrade-kind.sh
  test/generate-upstream-cert.sh
Labels: lgtm, approved, size/XL

#806 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#808 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#809 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL
