Repository knative-extensions/net-kourier, pull requests merged in 2022-09, with the labels that each got.

#912 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#911 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#915 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/configmap/load.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#917 Drop namespace from net-kourier ClusterRole
  config/200-serviceaccount.yaml
Labels: lgtm, approved, size/XS, ok-to-test, kind/cleanup

#921 Bump envoy image to 1.21 and add compatibility with 1.22
  .github/workflows/kind-e2e.yaml
  config/200-bootstrap.yaml
  config/300-gateway.yaml
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/listener.go
Labels: lgtm, approved, size/S, kind/enhancement

#922 Fix psp in config manifests
  config/300-controller.yaml
  config/300-gateway.yaml
  test/config/chaosduck.yaml
Labels: lgtm, approved, size/S

#919 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#920 Add keepalive config in bootstrap.yaml
  config/200-bootstrap.yaml
Labels: lgtm, approved, size/S

#924 Remove deprecated empty fields in bootstrap.yaml
  config/200-bootstrap.yaml
Labels: lgtm, approved, size/XS

#927 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
