Repository knative-extensions/net-kourier, pull requests merged in 2022-10, with the labels that each got.

#928 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#930 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#932 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#934 Run envoy as non-root
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#933 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#935 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#938 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S
