Repository knative-extensions/net-kourier, pull requests merged in 2022-06, with the labels that each got.

#851 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#850 Fix net api deprecation
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/controller.go
Labels: lgtm, size/M, approved

#854 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#857 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#858 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#859 bump kind and k8s versions in kind-e2e tests
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, size/M, approved

#855 Use `internal-encryption` to deploy internal certificates automatically
  .github/workflows/kind-e2e-upgrade.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/config/store.go
  test/config/tls/config-network.yaml
  test/generate-upstream-cert.sh
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/key_pair.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#861 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#863 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review
