Repository knative-extensions/net-kourier, pull requests merged in 2022-12, with the labels that each got.

#955 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#958 Bump Maistra image version to 2.3
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/S

#962 [release-1.7] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: lgtm, approved, size/XS

#963 [release-1.6] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: lgtm, approved, size/XS

#961 [release-1.8] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: lgtm, approved, size/XS

#965 [release-1.7] gofmt 1.19
  pkg/generator/ingress_translator.go
  test/config/extauthz/http/src/main.go
Labels: lgtm, approved, size/XS

#964 [release-1.8] gofmt 1.19
  pkg/generator/ingress_translator.go
  test/config/extauthz/http/src/main.go
Labels: lgtm, approved, size/XS

#966 [release-1.6] gofmt 1.19 & add some nolint for test code
  pkg/generator/ingress_translator.go
  test/config/extauthz/http/src/main.go
Labels: lgtm, approved, size/XS

#969 Add upgrade strategy
  config/300-controller.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#967 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, skip-review
