Repository knative-extensions/net-kourier, pull requests merged in 2023-08, with the labels that each got.

#1082 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1083 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1085 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1087 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1088 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1090 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1092 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/prometheus/statsd_exporter/pkg/LICENSE
  third_party/VENDOR-LICENSE/github.com/prometheus/statsd_exporter/pkg/NOTICE
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/github.com/prometheus/statsd_exporter/pkg/level/level.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/escape.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/fsm/dump.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/fsm/fsm.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/pubsub.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/shared_buffer_pool.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1076 Fix envoy deprecated fields
  config/200-bootstrap.yaml
  pkg/envoy/api/headers.go
  pkg/envoy/api/headers_test.go
  pkg/envoy/api/weighted_cluster_test.go
Labels: lgtm, approved, size/S, kind/cleanup

#1093 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1094 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: lgtm, approved, size/S
