Repository knative-extensions/net-kourier, pull requests merged in 2023-06, with the labels that each got.

#1057 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1058 Set TLS 1.3 for min and max versions
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, approved, size/XS

#1060 Get certificate reconciler from networking instead of control-protocol
  go.mod
  go.sum
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/retry/main.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1061 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1064 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1065 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1067 Stop using NodePort on KinD test
  .github/workflows/kind-e2e.yaml
  test/e2e-upgrade-kind.sh
Labels: lgtm, approved, size/XS

#1069 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
