Repository knative-extensions/net-kourier, pull requests merged in 2023-11, with the labels that each got.

#1150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1149 Increase kourier controller CPU limit
  config/300-controller.yaml
Labels: lgtm, approved, size/XS

#1155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1157 Increase Kourier gateway CPU limit
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#1160 Make SECURITY.md consistent
  SECURITY.md
Labels: lgtm, approved, size/XS

#1163 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1161 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1165 Drop testing on k8s v1.26
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/XS

#1166 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
