Repository knative-extensions/net-kourier, pull requests merged in 2023-07, with the labels that each got.

#1070 update README.md
  README.md
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation, kind/cleanup

#1072 Revert "Add startup probe for controller (#1063)"
  config/300-controller.yaml
Labels: lgtm, approved, size/XS

#1074 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1073 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.opencensus.io/Makefile
  vendor/go.opencensus.io/opencensus.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/stats/doc.go
  vendor/go.opencensus.io/stats/internal/record.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/doc.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/tag/profile_19.go
  vendor/go.opencensus.io/tag/profile_not19.go
  vendor/go.opencensus.io/trace/doc.go
  vendor/go.opencensus.io/trace/lrumap.go
  vendor/go.opencensus.io/trace/trace_go11.go
  vendor/go.opencensus.io/trace/trace_nongo11.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1075 Use informer for startupTranslator
  pkg/reconciler/ingress/controller.go
Labels: lgtm, size/M, approved

#1077 Drop rollout for e2e test which updates config-kourier
  test/e2e-kind.sh
Labels: lgtm, approved, size/XS, kind/cleanup

#1078 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1079 Fix an issue where getReadyIngresses was not loading ready ingresses at startup
  config/300-controller.yaml
  pkg/reconciler/ingress/controller.go
Labels: lgtm, approved, size/S, kind/bug
