Repository knative-extensions/net-kourier, pull requests merged in 2023-02, with the labels that each got.

#985 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#986 Use serving-writers and reviewers teams
  OWNERS
Labels: lgtm, approved, size/XS

#987 Allow to configure cipher suites for TLS external listener
  README.md
  config/200-config.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/config/zz_generated.deepcopy.go
  pkg/envoy/api/listener.go
  pkg/envoy/api/listener_test.go
  pkg/generator/caches.go
  test/e2e-kind.sh
  test/tls/cipher_test.go
Labels: lgtm, approved, size/L

#988 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#990 Add a hpa and pdb for kourier-gateway
  config/300-gateway.yaml
Labels: lgtm, size/M, approved, kind/enhancement

#995 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#997 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#996 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#999 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1000 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1002 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1006 [release-1.8] trigger to build release with go1.19.6
  go.mod
Labels: lgtm, approved, size/XS

#1007 [release-1.9] trigger to build release with go1.19.6
  go.mod
Labels: lgtm, approved, size/XS
