Repository knative-extensions/net-kourier, pull requests merged in 2023-01, with the labels that each got.

#959 Determine internal-encryption via KIngress
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  test/upgrade/probe_test.go
Labels: lgtm, size/M, approved

#973 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#975 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#949 Use new key names for internal encryption secret
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  test/generate-upstream-cert.sh
Labels: lgtm, approved, size/S, kind/cleanup

#943 Fix deprecated warning
  config/200-bootstrap.yaml
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
Labels: lgtm, approved, size/L

#970 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#977 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#976 Bump envoy image version to 1.22 and 1.23
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/S

#978 Add prometheus annotations to net-kourier
  config/300-controller.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#889 Add trusted hops parameters support
  config/200-config.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
Labels: lgtm, size/M, approved, ok-to-test, kind/enhancement

#979 Add resource requests/limits
  config/300-controller.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/S

#982 Bump envoy version to 1.23 and 1.24
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS
