Repository knative-extensions/net-kourier, pull requests merged in 2023-09, with the labels that each got.

#1101 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1099 Revert changes from traffic-isolation PoC
  README.md
  config/200-config.yaml
  config/200-serviceaccount.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/generator/caches.go
  pkg/generator/caches_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, kind/removal

#1102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1105 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1108 Do not use informer for startupTranslator
  pkg/reconciler/ingress/controller.go
Labels: lgtm, approved, size/XS

#1110 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1111 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1096 Bump envoy version to 1.25 and 1.26
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#1113 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1114 Bump golang and kind version
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/S

#1115 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1119 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1122 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1123 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1121 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1124 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/embed.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1125 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: lgtm, approved, size/L
