Repository knative-extensions/net-kourier, pull requests merged in 2023-04, with the labels that each got.

#1016 :broom: Add debug log for cluster
  pkg/generator/ingress_translator.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1019 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1014 Bump CI configs
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/S

#1021 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1022 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1024 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1023 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#1026 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1031 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1028 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#1025 Fix keepalive interval
  pkg/envoy/server/xds_server.go
Labels: lgtm, approved, size/XS, ok-to-test, kind/bug

#1032 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1033 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1034 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1035 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
