Repository knative-extensions/net-kourier, pull requests merged in 2023-10, with the labels that each got.

#1116 Use aligned flags and secrets for `system-internal-tls`
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/reconciler/ingress/config/store.go
  test/config/tls/config-network.yaml
  test/e2e-kind.sh
  test/generate-upstream-cert.sh
  test/generate-wildcard-cert.sh
  test/upgrade/probe_test.go
Labels: lgtm, approved, size/L, kind/cleanup

#1130 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1132 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1133 [release-1.10] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: lgtm, approved, size/XS

#1131 Rename autoTLS to external-domain-tls
  README.md
Labels: lgtm, approved, size/XS

#1135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1138 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1140 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1143 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1147 [release-1.11][CVE-2023-44487] Update grpc to v1.56.3
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL
