Repository knative-extensions/net-kourier, pull requests merged in 2024-04, with the labels that each got.

#1235 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1237 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1236 Increase gateway memory limit
  config/300-gateway.yaml
Labels: lgtm, approved, size/XS

#1238 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1239 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1240 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/runtime/main.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1241 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1244 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1246 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
