Repository knative-extensions/net-kourier, pull requests merged in 2024-09, with the labels that each got.

#1284 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#1285 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1286 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_hurd.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term_windows.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1288 Bump envoy version and use shared go version
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
  config/300-gateway.yaml
Labels: lgtm, approved, size/S

#1291 Fix lint errors
  pkg/config/ext_authz.go
  pkg/generator/caches.go
  pkg/generator/cluster_cache_test.go
  pkg/generator/ingress_translator.go
  pkg/generator/ingress_translator_test.go
  pkg/generator/sni.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
  test/proxyprotocol/proxyprotocol_test.go
  test/tracing/tracing_test.go
Labels: lgtm, size/M, approved, kind/cleanup

#1290 Expose use_remote_address
  config/200-config.yaml
  pkg/config/config.go
  pkg/config/configmap.go
  pkg/config/configmap_test.go
  pkg/envoy/api/http_connection_manager.go
  pkg/envoy/api/http_connection_manager_test.go
Labels: lgtm, size/M, approved

#1292 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/crd.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
