Repository knative-extensions/net-kourier, pull requests merged in 2024-02, with the labels that each got.

#1198 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1204 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1205 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1206 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1207 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1208 drop k8s 1.27 from kind testing
  .github/workflows/kind-e2e-upgrade.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, approved, size/XS

#1213 bump cluster version to 1.28 in e2e scripts
  test/e2e-tests.sh
Labels: lgtm, approved, size/XS

#1214 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1216 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/interface.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/expansion_generated.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, ok-to-test
