Repository knative-extensions/net-kourier, pull requests merged in 2024-07, with the labels that each got.

#1269 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1273 Use a different 'static' image that supports s390x and ppc
  .ko.yaml
Labels: lgtm, approved, size/XS

#1276 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
